# Generated by Django 6.0.5 on 2026-06-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_email_alter_customuser_username'),
        ('tenants', '0002_tenantmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
