# Generated by Django 6.0.5 on 2026-06-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role'),
        ('accounts', '0007_profile_tenant'),
    ]

    operations = [
    ]
