# Generated by Django 6.0.5 on 2026-06-29 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_inventory_transaction_table(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS inventory_inventorytransaction (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transaction_type VARCHAR(20) NOT NULL,
                quantity integer NOT NULL CHECK (quantity >= 0),
                created_at timestamp with time zone NOT NULL,
                inventory_id bigint NOT NULL,
                remarks_id bigint NULL,
                tenant_id bigint NULL
            );
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("tenants", "0003_tenant_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            ensure_inventory_transaction_table,
            migrations.RunPython.noop,
        ),

        migrations.AddField(
            model_name="inventorytransaction",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_transactions",
                to="tenants.tenant",
            ),
        ),

        migrations.AlterField(
            model_name="inventorytransaction",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="inventory.inventory",
            ),
        ),

        migrations.AlterField(
            model_name="inventorytransaction",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),

        migrations.AlterField(
            model_name="inventorytransaction",
            name="remarks",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]