# Generated by Django 6.0.5 on 2026-06-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_options_inventory_updated_at'),
        ('products', '0004_alter_product_image'),
        ('tenants', '0001_initial'),
        ('warehouses', '0003_alter_warehouse_options_warehouse_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_product_warehouse',
        ),
        migrations.AddField(
            model_name='inventory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'warehouse'), name='unique_tenant_product_warehouse'),
        ),
    ]
