# Generated by Django 6.0.5 on 2026-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(default='Kathmandu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
