# Generated by Django 6.0.5 on 2026-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(default='Kathmandu', max_length=100),
        ),
    ]
