# Generated by Django 6.0.5 on 2026-06-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('cod', 'Cash on Delivery'), ('khalti', 'Khalti')], default='cod', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, help_text='eSewa or Khalti transaction ID after successful payment', max_length=255, null=True, unique=True),
        ),
    ]
