# Generated by Django 6.0.5 on 2026-07-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_invoice_options_remove_invoice_discount_and_more'),
    ]

    operations = [
    ]
