# Generated by Django 6.0.4 on 2026-07-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_delivery_address'),
        ('orders', '0011_order_delivery_address_order_delivery_latitude_and_more'),
    ]

    operations = [
    ]
