# Generated by Django 6.0.5 on 2026-07-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_merge_20260713_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_longitude',
        ),
    ]
