# Generated by Django 6.0.5 on 2026-07-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_merge_20260712_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
