# Generated by Django 6.0.5 on 2026-06-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_quantity'),
        ('products', '0007_remove_product_is_active'),
    ]

    operations = [
    ]
