# Generated by Django 6.0.5 on 2026-06-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20260626_1704'),
        ('products', '0008_merge_20260626_1707'),
    ]

    operations = [
    ]
